#:kivy 2.2.1

RootManager:
    Dashboard:
    Inventory:
    Sales:

<Dashboard>:
    name: 'dashboard'
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: root.welcome
            font_size: '22sp'
        Button:
            text: 'المخزون'
            on_release: app.root.current = 'inventory'
        Button:
            text: 'المبيعات'
            on_release: app.root.current = 'sales'

<Inventory>:
    name: 'inventory'
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'إدارة المخزون'
        Button:
            text: 'عودة'
            on_release: app.root.current = 'dashboard'

<Sales>:
    name: 'sales'
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'المبيعات'
        Button:
            text: 'عودة'
            on_release: app.root.current = 'dashboard'