ScreenManager:
    LoginScreen:
    DashboardScreen:
    InventoryScreen:
    SalesScreen:
    ReportsScreen:
    ExpiryScreen:

<LoginScreen>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'تسجيل الدخول'
        TextInput:
            hint_text: 'اسم المستخدم'
        TextInput:
            hint_text: 'كلمة المرور'
            password: True
        Button:
            text: 'دخول'
            on_press: app.root.current = 'dashboard'
            
            
            #:import dp kivy.metrics.dp

ScreenManager:

    DashboardScreen:
        name: 'dashboard'

    InventoryScreen:
        name: 'inventory'

    SalesScreen:
        name: 'sales'

    CustomersScreen:
        name: 'customers'

    SuppliersScreen:
        name: 'suppliers'

    ReportsScreen:
        name: 'reports'


<DashboardScreen>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'لوحة التحكم'
            font_size: '22sp'


<InventoryScreen>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'إدارة الأدوية'
            font_size: '22sp'


<SalesScreen>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'فواتير المبيعات'
            font_size: '22sp'


<CustomersScreen>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'العملاء'
            font_size: '22sp'


<SuppliersScreen>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'الموردين'
            font_size: '22sp'


<ReportsScreen>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'التقارير'
            font_size: '22sp'